export const chatListData = [
    {
        userID: 1,
        chatID : 1,
        subject : '한국의 문화에 대한 이야기',
        summary: 'We talked about Korean culture. I especially enjoyed sharing opinions about K-pop. Next time, I would like to talk about Korean food culture. See you next time ',
        date: '2024-09-27',
        user_msg_cnt: 4,
    },
    {
        userID: 1,
        chatID : 2,
        subject : '주문할 때 사용하는 표현',
        summary: 'We talked about Korean culture. I especially enjoyed sharing opinions about K-pop. Next time, I would like to talk about Korean food culture. See you next time ',
        date: '2024-09-26',
        user_msg_cnt: 5,
    },
    {
        userID: 1,
        chatID : 3,
        subject : '야구에 대한 이야기',
        summary: 'We talked about Korean culture. I especially enjoyed sharing opinions about K-pop. Next time, I would like to talk about Korean food culture. See you next time ',
        date: '2024-09-25',
        user_msg_cnt: 5,
    },
    {
        userID: 1,
        chatID : 4,
        subject : '한국어를 공부할 때 어려운 점',
        summary: 'We talked about Korean culture. I especially enjoyed sharing opinions about K-pop. Next time, I would like to talk about Korean food culture. See you next time ',
        date: '2024-09-24',
        user_msg_cnt: 6,
    },
    {
        userID: 1,
        chatID : 5,
        subject : '한국어 어려움',
        summary: 'We talked about Korean culture. I especially enjoyed sharing opinions about K-pop. Next time, I would like to talk about Korean food culture. See you next time ',
        date: '2024-09-23',
        user_msg_cnt: 6,
    },
    {
        userID: 1,
        chatID : 6,
        subject : '한국어 어려움',
        summary: 'We talked about Korean culture. I especially enjoyed sharing opinions about K-pop. Next time, I would like to talk about Korean food culture. See you next time ',
        date: '2024-09-23',
        user_msg_cnt: 6,
    },
];
